package top.pancras.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-02T16:05:33.298+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://service.cxf.pancras.top/", name = "WeatherInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherInterface {

    @WebMethod
    @RequestWrapper(localName = "getWeatherByCity", targetNamespace = "http://service.cxf.pancras.top/", className = "top.pancras.cxf.client.GetWeatherByCity")
    @ResponseWrapper(localName = "getWeatherByCityResponse", targetNamespace = "http://service.cxf.pancras.top/", className = "top.pancras.cxf.client.GetWeatherByCityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<top.pancras.cxf.client.Weather> getWeatherByCity(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
